name: 'Main'

on:
  push:
    branches:
    - "main"
    - "docker"

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: create docker buildx worker
      run: docker buildx create --platform linux/arm64,linux/amd64,linux/armhf --use --buildkitd-flags '--allow-insecure-entitlement security.insecure' --name tournament-frontend

    - name: Connect to dockerhub
      run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}

    - uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.CLUSTER_SSH_KEY }}
    - name: add ssh key
      run: ssh-keyscan -H ${{secrets.CLUSTER_IP}} >> ~/.ssh/known_hosts

    #- name: clean images prune
    #  run: docker -H ssh://debian@${{secrets.CLUSTER_IP}} images prune
      
    - name: Build the Docker image
      run: docker -H ssh://debian@${{secrets.CLUSTER_IP}} build --pull -t ${{secrets.DOCKER_LOGIN}}/tournament-frontend --output type=registry .
